apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
storageConfig:                                                      
  registry:
    imageURL: {{ url_disconnected_registry }}:5000/mirror/oc-mirror-metadata
    skipTLS: false
mirror:
  platform:
    architectures:
      - amd64
    channels:
      - name: stable-4.12
        type: ocp
        minVersion: 4.12.39
        maxVersion: 4.12.39
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
      packages:
        - name: compliance-operator
          channels:
            - name: stable
        - name: container-security-operator
          channels:
            - name: stable-3.9
        - name: file-integrity-operator
          channels:
            - name: stable  
        - name: local-storage-operator
          channels:
            - name: stable  
        - name: ocs-operator
          channels:
            - name: stable-4.12
        - name: odf-operator
          channels:
            - name: stable-4.12
        - name: cluster-logging
          channels:
            - name: stable
        - name: elasticsearch-operator
          channels:
            - name: stable
        - name: redhat-oadp-operator
          channels:
            - name: stable-1.2
        - name: rhsso-operator
          channels:
            - name: stable
        - name: self-node-remediation
          channels:
            - name: stable
        - name: web-terminal
          channels:
            - name: fast
        - name: devspaces
          channels:
            - name: stable
        - name: advanced-cluster-management
          channels:
            - name: release-2.8
        - name: rhacs-operator
          channels:
            - name: stable
        - name: lvms-operator
          channels:
            - name: stable-4.12
        - name: odf-multicluster-orchestrator
          channels:
            - name: stable-4.12
        - name: odf-operator
          channels:
            - name: stable-4.12
        - name: quay-operator
          channels:
            - name: stable-3.9
        - name: quay-bridge-operator
          channels:
            - name: stable-3.9
        - name: openshift-pipelines-operator-rh
          channels:
            - name: latest
        - name: openshift-gitops-operator
          channels:
            - name: latest
        - name: kubernetes-nmstate-operator
        - name: mta-operator
          channels:
            - name: stable-v6.2
        - name: mtv-operator
          channels:
            - name: release-v2.5
        - name: nfd
          channels:
            - name: stable
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.12
      packages:
        - name: elasticsearch-eck-operator-certified
        - name: nvidia-network-operator
        - name: gpu-operator-certified
  additionalImages:
    - name: registry.redhat.io/ubi8/ubi:latest
    - name: registry.redhat.io/rhel8/support-tools
    - name: registry.redhat.io/openshift4/ose-must-gather:latest
    - name: quay.io/allenfouladi/httpd4:debug
