- hosts: localhost
  tasks:
  
  - name: Execute the script
    expect:
      command: ./install-config.sh
      responses:
        (?i)rsa: ""
        (?i)53: "allenfouladi.com"

  - name: Install OpenShift
    shell: openshift-install create cluster

  - name: Login as Kubeadmin
    shell: 'export KUBECONFIG=auth/kubeconfig'

  - name: Create user accounts
    shell: ./usergeneration.sh

  - name: Deploy ACM
    shell: 'oc apply -f https://raw.githubusercontent.com/afouladi7/acm/main/templates/acm-deploy.yaml'
    
  - name: Deploy OCS
    shell: 'oc apply -f https://raw.githubusercontent.com/afouladi7/openshift_shortcuts/main/TEMPLATES/ocs-deploy.yaml'

  - name: Sleep for 120 seconds and continue with play
    wait_for:
      timeout: 120
    delegate_to: localhost

  - name: Deploy MultiClusterHub
    shell: 'oc apply -f https://raw.githubusercontent.com/afouladi7/acm/main/templates/multiclusterhub.yaml'
    
  - name: Deploy 1TB EBS Volumes for OCS
    shell: 'oc apply -f https://raw.githubusercontent.com/afouladi7/openshift_shortcuts/main/TEMPLATES/storagecluster.yaml'    
